# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           /blog/:title/

# Setup
title:               Carla Suárez Tipán
tagline:             'Periodista y Desarrolladora'
url:                 https://carlasuarez.xyz
baseurl:             ''
paginate:            5
paginate_path:       /blog/page:num/
gems:
  - jekyll-paginate

# About/contact
author:
  name:              Carla Suárez
  url:               https://carlasuarez.xyz
  github:            https://github.com/carlast22
  linkedin:          https://linkedin.com/in/carlasuarez22
  twitter:           https://twitter.com/carlast22
  company:           https://www.thoughtworks.com/