# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           /:title/

# Setup
title:               Carla Suárez
tagline:             'Periodista y Desarrolladora'
description:         'Soy desarrolladora de software en <a href="https://www.thoughtworks.com/">ThoughtWorks</a>'
url:                 https://carlasuarez.xyz
baseurl:             ''
paginate:            5
paginate_path:       /blog/page:num/
gems:
  - jekyll-paginate

# About/contact
author:
  name:              Carla Suárez
  url:               https://carlasuarez.xyz
