# Site settings
title: Coding Lines
email: carlast22@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: carlast22
github_username:  carlast22

# Build settings
markdown: kramdown
