# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           /blog/:title/

# Setup
title:               Carla Suárez
tagline:             'Periodista y Desarrolladora'
description:         'Soy desarrolladora de software en <a href="http://www.thoughtworks.com/">ThoughtWorks</a>'
url:                 http://carlasuarez.xyz
baseurl:             ''
paginate:            5
gems:
  - jekyll-paginate-v2

# About/contact
author:
  name:              Carla Suárez
  url:               http://carlasuarez.xyz

# Custom vars
version:             1.0.0
